---
  accept:
    - application/json
  server:
    uri: localhost:3000
  routes:
    controllerRootUrl: '/api'
  logging:
    stdout:
      enabled: true
      level: debug
  port: 3000
  host: 'https://d6wn6bmjj722w.population.io'
  env: dev
